-- Icon loader for the pixelarticons set generated by `tools/icons.py` into
-- images/icons/<name>-<size>.pdi. See tools/icons.py for why that pack and
-- how the sizes are produced; only the name/size pairs it emits exist.
--
-- Icons are transparent-background images, so drawing one over a filled row
-- works: switch to Graphics.kDrawModeFillWhite first and the strokes invert
-- without punching a white box out of the highlight.

Icons = Icons or {}

local cache = {}

--- Returns the image for an icon, or nil if that name/size wasn't generated.
function Icons.get(name, size)
	local key = name .. "-" .. size
	local cached = cache[key]
	if cached ~= nil then return cached end

	local image = Graphics.image.new("images/icons/" .. key)
	cache[key] = image
	return image
end

--- Draws an icon with its top-left corner at x, y.
function Icons.draw(name, size, x, y)
	local image = Icons.get(name, size)
	if image ~= nil then image:draw(x, y) end
end

--- Draws an icon centered on x, y -- the usual call, since icons mostly sit
--- next to text whose vertical center is the thing worth aligning to.
function Icons.drawCentered(name, size, x, y)
	local image = Icons.get(name, size)
	if image ~= nil then image:draw(x - size // 2, y - size // 2) end
end
